use super::MetaMemorySnapshot;

impl MetaMemorySnapshot {
    pub fn saturating_sub(&self, earlier: &Self) -> Self {
        fn opt_sub(value: Option<u64>, earlier: Option<u64>) -> Option<u64> {
            match (value, earlier) {
                (Some(value), Some(earlier)) => Some(value.saturating_sub(earlier)),
                (Some(value), None) => Some(value),
                _ => None,
            }
        }

        macro_rules! sub {
            ($field:ident) => {
                self.$field.saturating_sub(earlier.$field)
            };
        }

        // Element-wise saturating sub for per-shard counter vectors.
        // Length difference is unexpected (snapshots come from the same
        // running process) but we tolerate it by truncating to the
        // shorter length and treating the missing elements as zero.
        fn sub_vec(current: &[u64], earlier: &[u64]) -> Vec<u64> {
            current
                .iter()
                .enumerate()
                .map(|(i, &c)| c.saturating_sub(earlier.get(i).copied().unwrap_or(0)))
                .collect()
        }

        Self {
            block_cache_capacity_bytes: self.block_cache_capacity_bytes,
            block_cache_usage_bytes: opt_sub(
                self.block_cache_usage_bytes,
                earlier.block_cache_usage_bytes,
            ),
            block_cache_pinned_usage_bytes: opt_sub(
                self.block_cache_pinned_usage_bytes,
                earlier.block_cache_pinned_usage_bytes,
            ),
            cur_size_all_mem_tables_bytes: sub!(cur_size_all_mem_tables_bytes),
            size_all_mem_tables_bytes: sub!(size_all_mem_tables_bytes),
            estimate_table_readers_mem_bytes: sub!(estimate_table_readers_mem_bytes),
            last_applied_lsn: sub!(last_applied_lsn),
            high_water_pages: sub!(high_water_pages),
            free_list_pages: sub!(free_list_pages),
            dedup_index_ssts: sub!(dedup_index_ssts),
            dedup_index_records: sub!(dedup_index_records),
            dedup_l0_distinct_fps: sub!(dedup_l0_distinct_fps),
            dedup_l0_approx_bytes: sub!(dedup_l0_approx_bytes),
            dedup_l1_entries: sub!(dedup_l1_entries),
            cache_hits: sub!(cache_hits),
            cache_misses: sub!(cache_misses),
            cache_evictions: sub!(cache_evictions),
            cache_current_pages: sub!(cache_current_pages),
            cache_capacity_bytes: self.cache_capacity_bytes,
            cache_pinned_pages: sub!(cache_pinned_pages),
            cache_pin_budget_bytes: self.cache_pin_budget_bytes,
            commit_attempts: sub!(commit_attempts),
            commit_success: sub!(commit_success),
            commit_errors: sub!(commit_errors),
            commit_empty: sub!(commit_empty),
            commit_ops: sub!(commit_ops),
            commit_ops_per_tx_max: self.commit_ops_per_tx_max,
            commit_wal_body_bytes: sub!(commit_wal_body_bytes),
            commit_wal_body_bytes_max: self.commit_wal_body_bytes_max,
            commit_total_us: sub!(commit_total_us),
            commit_total_max_us: self.commit_total_max_us,
            commit_wal_submit_us: sub!(commit_wal_submit_us),
            commit_wal_submit_max_us: self.commit_wal_submit_max_us,
            commit_drop_gate_wait_us: sub!(commit_drop_gate_wait_us),
            commit_drop_gate_wait_max_us: self.commit_drop_gate_wait_max_us,
            commit_apply_wait_us: sub!(commit_apply_wait_us),
            commit_apply_wait_max_us: self.commit_apply_wait_max_us,
            commit_apply_gate_wait_us: sub!(commit_apply_gate_wait_us),
            commit_apply_gate_wait_max_us: self.commit_apply_gate_wait_max_us,
            commit_finish_global_wait_us: sub!(commit_finish_global_wait_us),
            commit_finish_global_wait_max_us: self.commit_finish_global_wait_max_us,
            commit_apply_us: sub!(commit_apply_us),
            commit_apply_max_us: self.commit_apply_max_us,
            commit_direct_apply_count: sub!(commit_direct_apply_count),
            commit_direct_apply_us: sub!(commit_direct_apply_us),
            commit_direct_apply_max_us: self.commit_direct_apply_max_us,
            commit_apply_l2p_wait_us: sub!(commit_apply_l2p_wait_us),
            commit_apply_l2p_wait_max_us: self.commit_apply_l2p_wait_max_us,
            commit_apply_rc_enqueue_us: sub!(commit_apply_rc_enqueue_us),
            commit_apply_rc_enqueue_max_us: self.commit_apply_rc_enqueue_max_us,
            commit_apply_rc_wait_us: sub!(commit_apply_rc_wait_us),
            commit_apply_rc_wait_max_us: self.commit_apply_rc_wait_max_us,
            commit_apply_dedup_enqueue_us: sub!(commit_apply_dedup_enqueue_us),
            commit_apply_dedup_enqueue_max_us: self.commit_apply_dedup_enqueue_max_us,
            commit_apply_dedup_wait_us: sub!(commit_apply_dedup_wait_us),
            commit_apply_dedup_wait_max_us: self.commit_apply_dedup_wait_max_us,
            commit_plan_us: sub!(commit_plan_us),
            commit_plan_max_us: self.commit_plan_max_us,
            commit_encode_us: sub!(commit_encode_us),
            commit_encode_max_us: self.commit_encode_max_us,
            commit_unlogged_gate_wait_us: sub!(commit_unlogged_gate_wait_us),
            commit_unlogged_gate_wait_max_us: self.commit_unlogged_gate_wait_max_us,
            commit_checkpoint_unlogged_us: sub!(commit_checkpoint_unlogged_us),
            commit_checkpoint_unlogged_max_us: self.commit_checkpoint_unlogged_max_us,
            commit_read_held_us: sub!(commit_read_held_us),
            commit_read_held_max_us: self.commit_read_held_max_us,
            wal_submit_calls: sub!(wal_submit_calls),
            wal_submit_wait_us: sub!(wal_submit_wait_us),
            wal_submit_wait_max_us: self.wal_submit_wait_max_us,
            wal_queue_wait_us: sub!(wal_queue_wait_us),
            wal_queue_wait_max_us: self.wal_queue_wait_max_us,
            wal_writer_busy_us: sub!(wal_writer_busy_us),
            wal_writer_busy_max_us: self.wal_writer_busy_max_us,
            wal_wake_roundtrip_us: sub!(wal_wake_roundtrip_us),
            wal_wake_roundtrip_max_us: self.wal_wake_roundtrip_max_us,
            wal_batches: sub!(wal_batches),
            wal_records: sub!(wal_records),
            wal_bytes: sub!(wal_bytes),
            wal_rotates: sub!(wal_rotates),
            wal_fsyncs: sub!(wal_fsyncs),
            wal_write_us: sub!(wal_write_us),
            wal_write_max_us: self.wal_write_max_us,
            wal_fsync_us: sub!(wal_fsync_us),
            wal_fsync_max_us: self.wal_fsync_max_us,
            wal_batch_records_max: self.wal_batch_records_max,
            wal_batch_bytes_max: self.wal_batch_bytes_max,
            range_delete_calls: sub!(range_delete_calls),
            range_delete_success: sub!(range_delete_success),
            range_delete_errors: sub!(range_delete_errors),
            range_delete_noop: sub!(range_delete_noop),
            range_delete_captured_entries: sub!(range_delete_captured_entries),
            range_delete_chunks: sub!(range_delete_chunks),
            range_delete_total_us: sub!(range_delete_total_us),
            range_delete_total_max_us: self.range_delete_total_max_us,
            cleanup_calls: sub!(cleanup_calls),
            cleanup_success: sub!(cleanup_success),
            cleanup_errors: sub!(cleanup_errors),
            cleanup_noop: sub!(cleanup_noop),
            cleanup_pbas: sub!(cleanup_pbas),
            cleanup_hashes_found: sub!(cleanup_hashes_found),
            cleanup_forward_checks: sub!(cleanup_forward_checks),
            cleanup_tombstones_emitted: sub!(cleanup_tombstones_emitted),
            cleanup_tx_ops: sub!(cleanup_tx_ops),
            cleanup_total_us: sub!(cleanup_total_us),
            cleanup_total_max_us: self.cleanup_total_max_us,
            cleanup_scan_us: sub!(cleanup_scan_us),
            cleanup_scan_max_us: self.cleanup_scan_max_us,
            cleanup_forward_check_us: sub!(cleanup_forward_check_us),
            cleanup_forward_check_max_us: self.cleanup_forward_check_max_us,
            cleanup_commit_us: sub!(cleanup_commit_us),
            cleanup_commit_max_us: self.cleanup_commit_max_us,
            apply_l2p_put_count: sub!(apply_l2p_put_count),
            apply_l2p_put_us: sub!(apply_l2p_put_us),
            apply_l2p_put_max_us: self.apply_l2p_put_max_us,
            apply_l2p_delete_count: sub!(apply_l2p_delete_count),
            apply_l2p_delete_us: sub!(apply_l2p_delete_us),
            apply_l2p_delete_max_us: self.apply_l2p_delete_max_us,
            apply_l2p_remap_count: sub!(apply_l2p_remap_count),
            apply_l2p_remap_us: sub!(apply_l2p_remap_us),
            apply_l2p_remap_max_us: self.apply_l2p_remap_max_us,
            apply_l2p_remap_range_count: sub!(apply_l2p_remap_range_count),
            apply_l2p_remap_range_lbas: sub!(apply_l2p_remap_range_lbas),
            apply_l2p_remap_range_us: sub!(apply_l2p_remap_range_us),
            apply_l2p_remap_range_max_us: self.apply_l2p_remap_range_max_us,
            apply_l2p_range_delete_count: sub!(apply_l2p_range_delete_count),
            apply_l2p_range_delete_us: sub!(apply_l2p_range_delete_us),
            apply_l2p_range_delete_max_us: self.apply_l2p_range_delete_max_us,
            apply_refcount_count: sub!(apply_refcount_count),
            apply_refcount_us: sub!(apply_refcount_us),
            apply_refcount_max_us: self.apply_refcount_max_us,
            apply_dedup_count: sub!(apply_dedup_count),
            apply_dedup_us: sub!(apply_dedup_us),
            apply_dedup_max_us: self.apply_dedup_max_us,
            dedup_lane_tasks: sub!(dedup_lane_tasks),
            dedup_lane_ops: sub!(dedup_lane_ops),
            dedup_lane_ready_queue_wait_us: sub!(dedup_lane_ready_queue_wait_us),
            dedup_lane_ready_queue_wait_max_us: self.dedup_lane_ready_queue_wait_max_us,
            dedup_lane_exec_us: sub!(dedup_lane_exec_us),
            dedup_lane_exec_max_us: self.dedup_lane_exec_max_us,
            dedup_lane_idle_us: sub!(dedup_lane_idle_us),
            dedup_lane_idle_max_us: self.dedup_lane_idle_max_us,
            dedup_lane_wakeups: sub!(dedup_lane_wakeups),
            dedup_lane_empty_wakeups: sub!(dedup_lane_empty_wakeups),
            dedup_lane_burst_total: sub!(dedup_lane_burst_total),
            dedup_lane_burst_max: self.dedup_lane_burst_max,
            dedup_lane_queue_depth_max: self.dedup_lane_queue_depth_max,
            l2p_apply_lane_tasks: sub!(l2p_apply_lane_tasks),
            l2p_apply_lane_queue_depth_max: self.l2p_apply_lane_queue_depth_max,
            l2p_apply_lane_queue_wait_us: sub!(l2p_apply_lane_queue_wait_us),
            l2p_apply_lane_queue_wait_max_us: self.l2p_apply_lane_queue_wait_max_us,
            l2p_apply_lane_exec_us: sub!(l2p_apply_lane_exec_us),
            l2p_apply_lane_exec_max_us: self.l2p_apply_lane_exec_max_us,
            l2p_apply_lane_idle_us: sub!(l2p_apply_lane_idle_us),
            l2p_apply_lane_idle_max_us: self.l2p_apply_lane_idle_max_us,
            l2p_apply_lane_wakeups: sub!(l2p_apply_lane_wakeups),
            l2p_apply_lane_empty_wakeups: sub!(l2p_apply_lane_empty_wakeups),
            l2p_apply_lane_burst_total: sub!(l2p_apply_lane_burst_total),
            l2p_apply_lane_burst_max: self.l2p_apply_lane_burst_max,
            rc_apply_lane_tasks: sub!(rc_apply_lane_tasks),
            rc_apply_lane_queue_depth_max: self.rc_apply_lane_queue_depth_max,
            rc_apply_lane_queue_wait_us: sub!(rc_apply_lane_queue_wait_us),
            rc_apply_lane_queue_wait_max_us: self.rc_apply_lane_queue_wait_max_us,
            rc_apply_lane_exec_us: sub!(rc_apply_lane_exec_us),
            rc_apply_lane_exec_max_us: self.rc_apply_lane_exec_max_us,
            rc_apply_lane_idle_us: sub!(rc_apply_lane_idle_us),
            rc_apply_lane_idle_max_us: self.rc_apply_lane_idle_max_us,
            rc_apply_lane_pending_set_wait_us: sub!(rc_apply_lane_pending_set_wait_us),
            rc_apply_lane_pending_set_wait_max_us: self.rc_apply_lane_pending_set_wait_max_us,
            rc_apply_lane_wakeups: sub!(rc_apply_lane_wakeups),
            rc_apply_lane_empty_wakeups: sub!(rc_apply_lane_empty_wakeups),
            rc_apply_lane_burst_total: sub!(rc_apply_lane_burst_total),
            rc_apply_lane_burst_max: self.rc_apply_lane_burst_max,
            l2p_apply_lane_shard_tasks: sub_vec(
                &self.l2p_apply_lane_shard_tasks,
                &earlier.l2p_apply_lane_shard_tasks,
            ),
            l2p_apply_lane_shard_queue_depth_max: self.l2p_apply_lane_shard_queue_depth_max.clone(),
            l2p_apply_lane_shard_queue_wait_us: sub_vec(
                &self.l2p_apply_lane_shard_queue_wait_us,
                &earlier.l2p_apply_lane_shard_queue_wait_us,
            ),
            l2p_apply_lane_shard_queue_wait_max_us: self
                .l2p_apply_lane_shard_queue_wait_max_us
                .clone(),
            l2p_apply_lane_shard_exec_us: sub_vec(
                &self.l2p_apply_lane_shard_exec_us,
                &earlier.l2p_apply_lane_shard_exec_us,
            ),
            l2p_apply_lane_shard_exec_max_us: self.l2p_apply_lane_shard_exec_max_us.clone(),
            l2p_apply_lane_shard_idle_us: sub_vec(
                &self.l2p_apply_lane_shard_idle_us,
                &earlier.l2p_apply_lane_shard_idle_us,
            ),
            l2p_apply_lane_shard_wakeups: sub_vec(
                &self.l2p_apply_lane_shard_wakeups,
                &earlier.l2p_apply_lane_shard_wakeups,
            ),
            l2p_apply_lane_shard_empty_wakeups: sub_vec(
                &self.l2p_apply_lane_shard_empty_wakeups,
                &earlier.l2p_apply_lane_shard_empty_wakeups,
            ),
            l2p_apply_lane_shard_burst_total: sub_vec(
                &self.l2p_apply_lane_shard_burst_total,
                &earlier.l2p_apply_lane_shard_burst_total,
            ),
            l2p_apply_lane_shard_burst_max: self.l2p_apply_lane_shard_burst_max.clone(),
            rc_apply_lane_shard_tasks: sub_vec(
                &self.rc_apply_lane_shard_tasks,
                &earlier.rc_apply_lane_shard_tasks,
            ),
            rc_apply_lane_shard_queue_depth_max: self.rc_apply_lane_shard_queue_depth_max.clone(),
            rc_apply_lane_shard_queue_wait_us: sub_vec(
                &self.rc_apply_lane_shard_queue_wait_us,
                &earlier.rc_apply_lane_shard_queue_wait_us,
            ),
            rc_apply_lane_shard_queue_wait_max_us: self
                .rc_apply_lane_shard_queue_wait_max_us
                .clone(),
            rc_apply_lane_shard_exec_us: sub_vec(
                &self.rc_apply_lane_shard_exec_us,
                &earlier.rc_apply_lane_shard_exec_us,
            ),
            rc_apply_lane_shard_exec_max_us: self.rc_apply_lane_shard_exec_max_us.clone(),
            rc_apply_lane_shard_idle_us: sub_vec(
                &self.rc_apply_lane_shard_idle_us,
                &earlier.rc_apply_lane_shard_idle_us,
            ),
            rc_apply_lane_shard_pending_set_wait_us: sub_vec(
                &self.rc_apply_lane_shard_pending_set_wait_us,
                &earlier.rc_apply_lane_shard_pending_set_wait_us,
            ),
            rc_apply_lane_shard_pending_set_wait_max_us: self
                .rc_apply_lane_shard_pending_set_wait_max_us
                .clone(),
            rc_apply_lane_shard_wakeups: sub_vec(
                &self.rc_apply_lane_shard_wakeups,
                &earlier.rc_apply_lane_shard_wakeups,
            ),
            rc_apply_lane_shard_empty_wakeups: sub_vec(
                &self.rc_apply_lane_shard_empty_wakeups,
                &earlier.rc_apply_lane_shard_empty_wakeups,
            ),
            rc_apply_lane_shard_burst_total: sub_vec(
                &self.rc_apply_lane_shard_burst_total,
                &earlier.rc_apply_lane_shard_burst_total,
            ),
            rc_apply_lane_shard_burst_max: self.rc_apply_lane_shard_burst_max.clone(),
            dedup_apply_guard_count: sub!(dedup_apply_guard_count),
            dedup_apply_guard_us: sub!(dedup_apply_guard_us),
            dedup_apply_guard_max_us: self.dedup_apply_guard_max_us,
            dedup_apply_forward_put_count: sub!(dedup_apply_forward_put_count),
            dedup_apply_forward_put_us: sub!(dedup_apply_forward_put_us),
            dedup_apply_forward_put_max_us: self.dedup_apply_forward_put_max_us,
            dedup_apply_forward_delete_count: sub!(dedup_apply_forward_delete_count),
            dedup_apply_forward_delete_us: sub!(dedup_apply_forward_delete_us),
            dedup_apply_forward_delete_max_us: self.dedup_apply_forward_delete_max_us,
            dedup_apply_reverse_put_count: sub!(dedup_apply_reverse_put_count),
            dedup_apply_reverse_put_us: sub!(dedup_apply_reverse_put_us),
            dedup_apply_reverse_put_max_us: self.dedup_apply_reverse_put_max_us,
            dedup_apply_reverse_delete_count: sub!(dedup_apply_reverse_delete_count),
            dedup_apply_reverse_delete_us: sub!(dedup_apply_reverse_delete_us),
            dedup_apply_reverse_delete_max_us: self.dedup_apply_reverse_delete_max_us,
            dedup_put_l0_insert_us: sub!(dedup_put_l0_insert_us),
            dedup_put_l0_insert_max_us: self.dedup_put_l0_insert_max_us,
            dedup_put_l1_put_us: sub!(dedup_put_l1_put_us),
            dedup_put_l1_put_max_us: self.dedup_put_l1_put_max_us,
            dedup_put_cuckoo_update_existing_us: sub!(dedup_put_cuckoo_update_existing_us),
            dedup_put_cuckoo_update_existing_max_us: self.dedup_put_cuckoo_update_existing_max_us,
            dedup_put_cuckoo_free_slots_us: sub!(dedup_put_cuckoo_free_slots_us),
            dedup_put_cuckoo_free_slots_max_us: self.dedup_put_cuckoo_free_slots_max_us,
            dedup_put_cuckoo_try_insert_empty_us: sub!(dedup_put_cuckoo_try_insert_empty_us),
            dedup_put_cuckoo_try_insert_empty_max_us: self.dedup_put_cuckoo_try_insert_empty_max_us,
            dedup_put_cuckoo_evict_and_insert_us: sub!(dedup_put_cuckoo_evict_and_insert_us),
            dedup_put_cuckoo_evict_and_insert_max_us: self.dedup_put_cuckoo_evict_and_insert_max_us,
            dedup_put_cuckoo_page_read_cache_wait_us: sub!(
                dedup_put_cuckoo_page_read_cache_wait_us
            ),
            dedup_put_cuckoo_page_read_cache_wait_max_us: self
                .dedup_put_cuckoo_page_read_cache_wait_max_us,
            dedup_put_cuckoo_page_alloc_us: sub!(dedup_put_cuckoo_page_alloc_us),
            dedup_put_cuckoo_page_alloc_max_us: self.dedup_put_cuckoo_page_alloc_max_us,
            dedup_put_cuckoo_page_write_publish_us: sub!(dedup_put_cuckoo_page_write_publish_us),
            dedup_put_cuckoo_page_write_publish_max_us: self
                .dedup_put_cuckoo_page_write_publish_max_us,
            dedup_put_cuckoo_bucket_lock_wait_us: sub!(dedup_put_cuckoo_bucket_lock_wait_us),
            dedup_put_cuckoo_bucket_lock_wait_max_us: self.dedup_put_cuckoo_bucket_lock_wait_max_us,
            l2p_get_calls: sub!(l2p_get_calls),
            l2p_get_lock_wait_us: sub!(l2p_get_lock_wait_us),
            l2p_get_lock_wait_max_us: self.l2p_get_lock_wait_max_us,
            l2p_get_tree_walk_us: sub!(l2p_get_tree_walk_us),
            l2p_get_tree_walk_max_us: self.l2p_get_tree_walk_max_us,
            l2p_multi_get_calls: sub!(l2p_multi_get_calls),
            l2p_multi_get_lbas: sub!(l2p_multi_get_lbas),
            l2p_multi_get_pin_us: sub!(l2p_multi_get_pin_us),
            l2p_multi_get_pin_max_us: self.l2p_multi_get_pin_max_us,
            l2p_multi_get_volume_us: sub!(l2p_multi_get_volume_us),
            l2p_multi_get_volume_max_us: self.l2p_multi_get_volume_max_us,
            l2p_multi_get_sort_us: sub!(l2p_multi_get_sort_us),
            l2p_multi_get_sort_max_us: self.l2p_multi_get_sort_max_us,
            l2p_multi_get_view_us: sub!(l2p_multi_get_view_us),
            l2p_multi_get_view_max_us: self.l2p_multi_get_view_max_us,
            l2p_multi_get_tree_us: sub!(l2p_multi_get_tree_us),
            l2p_multi_get_tree_max_us: self.l2p_multi_get_tree_max_us,
            flush_calls: sub!(flush_calls),
            flush_total_us: sub!(flush_total_us),
            flush_total_max_us: self.flush_total_max_us,
            flush_calls_steady: sub!(flush_calls_steady),
            flush_total_us_steady: sub!(flush_total_us_steady),
            flush_total_max_us_steady: self.flush_total_max_us_steady,
            flush_calls_forced: sub!(flush_calls_forced),
            flush_total_us_forced: sub!(flush_total_us_forced),
            flush_total_max_us_forced: self.flush_total_max_us_forced,
            flush_gate_wait_us: sub!(flush_gate_wait_us),
            flush_gate_wait_max_us: self.flush_gate_wait_max_us,
            flush_gate_hold_us: sub!(flush_gate_hold_us),
            flush_gate_hold_max_us: self.flush_gate_hold_max_us,
            flush_dedup_drain_us: sub!(flush_dedup_drain_us),
            flush_dedup_drain_max_us: self.flush_dedup_drain_max_us,
            flush_l2p_fold_us: sub!(flush_l2p_fold_us),
            flush_l2p_fold_max_us: self.flush_l2p_fold_max_us,
            l2p_buffer_compaction_cycles: sub!(l2p_buffer_compaction_cycles),
            l2p_buffer_compaction_entries: sub!(l2p_buffer_compaction_entries),
            l2p_buffer_compaction_us: sub!(l2p_buffer_compaction_us),
            l2p_buffer_compaction_max_us: self.l2p_buffer_compaction_max_us,
            l2p_buffer_compaction_leaves: sub!(l2p_buffer_compaction_leaves),
            l2p_buffer_compaction_chunks: sub!(l2p_buffer_compaction_chunks),
            l2p_buffer_compaction_plan_us: sub!(l2p_buffer_compaction_plan_us),
            l2p_buffer_compaction_plan_max_us: self.l2p_buffer_compaction_plan_max_us,
            l2p_buffer_compaction_tree_wait_us: sub!(l2p_buffer_compaction_tree_wait_us),
            l2p_buffer_compaction_tree_wait_max_us: self.l2p_buffer_compaction_tree_wait_max_us,
            l2p_buffer_compaction_apply_us: sub!(l2p_buffer_compaction_apply_us),
            l2p_buffer_compaction_apply_max_us: self.l2p_buffer_compaction_apply_max_us,
            l2p_buffer_compaction_publish_us: sub!(l2p_buffer_compaction_publish_us),
            l2p_buffer_compaction_publish_max_us: self.l2p_buffer_compaction_publish_max_us,
            l2p_buffer_compaction_finish_us: sub!(l2p_buffer_compaction_finish_us),
            l2p_buffer_compaction_finish_max_us: self.l2p_buffer_compaction_finish_max_us,
            l2p_prefold_attempts: sub!(l2p_prefold_attempts),
            l2p_prefold_completed: sub!(l2p_prefold_completed),
            l2p_prefold_skipped: sub!(l2p_prefold_skipped),
            l2p_prefold_errors: sub!(l2p_prefold_errors),
            l2p_prefold_us: sub!(l2p_prefold_us),
            l2p_prefold_max_us: self.l2p_prefold_max_us,
            l2p_prefold_wait_us: sub!(l2p_prefold_wait_us),
            l2p_prefold_wait_max_us: self.l2p_prefold_wait_max_us,
            flush_sample_us: sub!(flush_sample_us),
            flush_sample_max_us: self.flush_sample_max_us,
            flush_sample_us_steady: sub!(flush_sample_us_steady),
            flush_sample_max_us_steady: self.flush_sample_max_us_steady,
            flush_sample_us_forced: sub!(flush_sample_us_forced),
            flush_sample_max_us_forced: self.flush_sample_max_us_forced,
            flush_sample_l2p_dirty_pages: sub!(flush_sample_l2p_dirty_pages),
            flush_sample_l2p_dirty_pages_max: self.flush_sample_l2p_dirty_pages_max,
            flush_sample_rc_drained_deltas: sub!(flush_sample_rc_drained_deltas),
            flush_sample_rc_drained_deltas_max: self.flush_sample_rc_drained_deltas_max,
            flush_sample_rc_fresh_pages: sub!(flush_sample_rc_fresh_pages),
            flush_sample_rc_fresh_pages_max: self.flush_sample_rc_fresh_pages_max,
            flush_sample_lock_us: sub!(flush_sample_lock_us),
            flush_sample_lock_max_us: self.flush_sample_lock_max_us,
            flush_sample_l2p_walk_us: sub!(flush_sample_l2p_walk_us),
            flush_sample_l2p_walk_max_us: self.flush_sample_l2p_walk_max_us,
            flush_sample_rc_drain_us: sub!(flush_sample_rc_drain_us),
            flush_sample_rc_drain_max_us: self.flush_sample_rc_drain_max_us,
            rc_drainer_cycles: sub!(rc_drainer_cycles),
            rc_drainer_drained_entries: sub!(rc_drainer_drained_entries),
            rc_drainer_pages_built: sub!(rc_drainer_pages_built),
            rc_drainer_cycle_us: sub!(rc_drainer_cycle_us),
            rc_drainer_cycle_max_us: self.rc_drainer_cycle_max_us,
            rc_drainer_overlay_size_max_pages: self.rc_drainer_overlay_size_max_pages,
            rc_drainer_checkpoint_wait_us: sub!(rc_drainer_checkpoint_wait_us),
            rc_drainer_checkpoint_wait_max_us: self.rc_drainer_checkpoint_wait_max_us,
            rc_drainer_backpressure_fallbacks: sub!(rc_drainer_backpressure_fallbacks),
            rc_drainer_pool_refills: sub!(rc_drainer_pool_refills),
            rc_drainer_wakes: sub!(rc_drainer_wakes),
            rc_drainer_preempts: sub!(rc_drainer_preempts),
            flush_io_us: sub!(flush_io_us),
            flush_io_max_us: self.flush_io_max_us,
            flush_io_seal_us: sub!(flush_io_seal_us),
            flush_io_seal_max_us: self.flush_io_seal_max_us,
            flush_io_page_write_us: sub!(flush_io_page_write_us),
            flush_io_page_write_max_us: self.flush_io_page_write_max_us,
            flush_io_rc_meta_us: sub!(flush_io_rc_meta_us),
            flush_io_rc_meta_max_us: self.flush_io_rc_meta_max_us,
            flush_io_sync_us: sub!(flush_io_sync_us),
            flush_io_sync_max_us: self.flush_io_sync_max_us,
            flush_manifest_us: sub!(flush_manifest_us),
            flush_manifest_max_us: self.flush_manifest_max_us,
            flush_manifest_stage_us: sub!(flush_manifest_stage_us),
            flush_manifest_stage_max_us: self.flush_manifest_stage_max_us,
            flush_manifest_publish_us: sub!(flush_manifest_publish_us),
            flush_manifest_publish_max_us: self.flush_manifest_publish_max_us,
            flush_manifest_cleanup_us: sub!(flush_manifest_cleanup_us),
            flush_manifest_cleanup_max_us: self.flush_manifest_cleanup_max_us,
            flush_publish_barrier_wait_us: sub!(flush_publish_barrier_wait_us),
            flush_publish_barrier_wait_max_us: self.flush_publish_barrier_wait_max_us,
            flush_install_us: sub!(flush_install_us),
            flush_install_max_us: self.flush_install_max_us,
            flush_reclaim_us: sub!(flush_reclaim_us),
            flush_reclaim_max_us: self.flush_reclaim_max_us,
            flush_pages_written: sub!(flush_pages_written),
            flush_io_bytes_total: sub!(flush_io_bytes_total),
            flush_reclaim_budget_pages: sub!(flush_reclaim_budget_pages),
            flush_reclaim_selected_pages: sub!(flush_reclaim_selected_pages),
            flush_reclaim_reclaimed_pages: sub!(flush_reclaim_reclaimed_pages),
            flush_reclaim_blocked_pages: sub!(flush_reclaim_blocked_pages),
            async_reclaim_cycles: sub!(async_reclaim_cycles),
            async_reclaim_selected_pages: sub!(async_reclaim_selected_pages),
            async_reclaim_reclaimed_pages: sub!(async_reclaim_reclaimed_pages),
            async_reclaim_cycle_us: sub!(async_reclaim_cycle_us),
            async_reclaim_cycle_max_us: self.async_reclaim_cycle_max_us,
            lineage_gc_head_advanced: sub!(lineage_gc_head_advanced),
            lineage_gc_head_dead_pbas: sub!(lineage_gc_head_dead_pbas),
            lineage_gc_head_skipped_snap: sub!(lineage_gc_head_skipped_snap),
            lineage_gc_head_skipped_descendant: sub!(lineage_gc_head_skipped_descendant),
            lineage_gc_head_skipped_rc: sub!(lineage_gc_head_skipped_rc),
            lineage_gc_head_blocked_rc0_pbas: sub!(lineage_gc_head_blocked_rc0_pbas),
            lineage_gc_head_dropped_dedup_shared: sub!(lineage_gc_head_dropped_dedup_shared),
            meta_io_write_calls: sub!(meta_io_write_calls),
            meta_io_write_ops: sub!(meta_io_write_ops),
            meta_io_write_bytes: sub!(meta_io_write_bytes),
            meta_io_write_us: sub!(meta_io_write_us),
            meta_io_write_max_us: self.meta_io_write_max_us,
            meta_io_write_batch_ops_max: self.meta_io_write_batch_ops_max,
            meta_io_write_batch_bytes_max: self.meta_io_write_batch_bytes_max,
            meta_io_read_calls: sub!(meta_io_read_calls),
            meta_io_read_ops: sub!(meta_io_read_ops),
            meta_io_read_bytes: sub!(meta_io_read_bytes),
            meta_io_read_us: sub!(meta_io_read_us),
            meta_io_read_max_us: self.meta_io_read_max_us,
            meta_io_read_batch_ops_max: self.meta_io_read_batch_ops_max,
            meta_io_fsync_calls: sub!(meta_io_fsync_calls),
            meta_io_fsync_us: sub!(meta_io_fsync_us),
            meta_io_fsync_max_us: self.meta_io_fsync_max_us,
            meta_io_write_uring_lock_acquires: sub!(meta_io_write_uring_lock_acquires),
            meta_io_write_uring_lock_wait_us: sub!(meta_io_write_uring_lock_wait_us),
            meta_io_write_uring_lock_wait_max_us: self.meta_io_write_uring_lock_wait_max_us,
            io_submitter_iterations: sub!(io_submitter_iterations),
            io_submitter_sqes_submitted: sub!(io_submitter_sqes_submitted),
            io_submitter_channel_pending_max: self.io_submitter_channel_pending_max,
            io_submitter_submit_batch_size_max: self.io_submitter_submit_batch_size_max,
            io_submitter_inflight_max: self.io_submitter_inflight_max,
            io_submitter_bg_deferred: sub!(io_submitter_bg_deferred),
            io_submitter_bg_inflight_max: self.io_submitter_bg_inflight_max,
            io_submitter_bg_deferred_max: self.io_submitter_bg_deferred_max,
            l2p_writeback_cycles: sub!(l2p_writeback_cycles),
            l2p_writeback_cycles_with_work: sub!(l2p_writeback_cycles_with_work),
            l2p_writeback_shards_flushed: sub!(l2p_writeback_shards_flushed),
            l2p_writeback_pages_promoted: sub!(l2p_writeback_pages_promoted),
            l2p_writeback_pages_kept_dirty: sub!(l2p_writeback_pages_kept_dirty),
            l2p_writeback_pages_written: sub!(l2p_writeback_pages_written),
            l2p_writeback_io_bytes_total: sub!(l2p_writeback_io_bytes_total),
            l2p_writeback_seal_us: sub!(l2p_writeback_seal_us),
            l2p_writeback_seal_max_us: self.l2p_writeback_seal_max_us,
            l2p_writeback_io_us: sub!(l2p_writeback_io_us),
            l2p_writeback_io_max_us: self.l2p_writeback_io_max_us,
            l2p_writeback_install_us: sub!(l2p_writeback_install_us),
            l2p_writeback_install_max_us: self.l2p_writeback_install_max_us,
            l2p_writeback_errors: sub!(l2p_writeback_errors),
            l2p_writeback_target_skips: sub!(l2p_writeback_target_skips),
            pending_dispatch: self.pending_dispatch,
            pending_deferred_free: self.pending_deferred_free,
            pending_dedup_lane_queue: self.pending_dedup_lane_queue,
            pending_l2p_apply_queue: self.pending_l2p_apply_queue,
            pending_l2p_private_pages: self.pending_l2p_private_pages,
            pending_l2p_retired_pages: self.pending_l2p_retired_pages,
            pending_l2p_pagebuf_total: self.pending_l2p_pagebuf_total,
            pending_l2p_pagebuf_dirty: self.pending_l2p_pagebuf_dirty,
            pending_rc_apply_queue: self.pending_rc_apply_queue,
            pending_rc_private_pages: self.pending_rc_private_pages,
            pending_rc_retired_pages: self.pending_rc_retired_pages,
            pending_rc_pagebuf_total: self.pending_rc_pagebuf_total,
            pending_rc_pagebuf_dirty: self.pending_rc_pagebuf_dirty,
        }
    }

    pub fn total_estimate_bytes(&self) -> Option<u64> {
        self.block_cache_usage_bytes.map(|block_cache| {
            block_cache
                .saturating_add(self.size_all_mem_tables_bytes)
                .saturating_add(self.estimate_table_readers_mem_bytes)
        })
    }
}
