use std::sync::atomic::{AtomicU64, Ordering};

use serde::Serialize;

use super::*;

impl EngineMetrics {
    pub fn snapshot(&self) -> EngineMetricsSnapshot {
        let load = |counter: &AtomicU64| counter.load(Ordering::Relaxed);
        EngineMetricsSnapshot {
            uptime_secs: self.started_at.elapsed().as_secs(),
            volume_create_ops: load(&self.volume_create_ops),
            volume_delete_ops: load(&self.volume_delete_ops),
            volume_open_ops: load(&self.volume_open_ops),
            volume_read_ops: load(&self.volume_read_ops),
            volume_read_bytes: load(&self.volume_read_bytes),
            volume_read_total_ns: load(&self.volume_read_total_ns),
            ublk_read_queue_wait_ns: load(&self.ublk_read_queue_wait_ns),
            ublk_read_worker_ns: load(&self.ublk_read_worker_ns),
            ublk_read_completion_wait_ns: load(&self.ublk_read_completion_wait_ns),
            volume_partial_read_ops: load(&self.volume_partial_read_ops),
            volume_write_ops: load(&self.volume_write_ops),
            volume_write_bytes: load(&self.volume_write_bytes),
            volume_write_total_ns: load(&self.volume_write_total_ns),
            ublk_write_queue_wait_ns: load(&self.ublk_write_queue_wait_ns),
            ublk_write_worker_ns: load(&self.ublk_write_worker_ns),
            ublk_write_completion_wait_ns: load(&self.ublk_write_completion_wait_ns),
            volume_partial_write_ops: load(&self.volume_partial_write_ops),
            zone_write_dispatches: load(&self.zone_write_dispatches),
            zone_submit_write_ns: load(&self.zone_submit_write_ns),
            zone_worker_write_ns: load(&self.zone_worker_write_ns),
            zone_write_split_ops: load(&self.zone_write_split_ops),
            zone_write_lbas: load(&self.zone_write_lbas),
            zone_read_dispatches: load(&self.zone_read_dispatches),
            buffer_appends: load(&self.buffer_appends),
            buffer_append_bytes: load(&self.buffer_append_bytes),
            buffer_write_ops: load(&self.buffer_write_ops),
            buffer_write_bytes: load(&self.buffer_write_bytes),
            buffer_append_total_ns: load(&self.buffer_append_total_ns),
            buffer_append_prepare_ns: load(&self.buffer_append_prepare_ns),
            buffer_append_log_write_ns: load(&self.buffer_append_log_write_ns),
            buffer_append_wait_durable_ns: load(&self.buffer_append_wait_durable_ns),
            buffer_sync_batches: load(&self.buffer_sync_batches),
            buffer_sync_batch_ns: load(&self.buffer_sync_batch_ns),
            buffer_sync_sleep_ns: load(&self.buffer_sync_sleep_ns),
            buffer_sync_epochs_committed: load(&self.buffer_sync_epochs_committed),
            buffer_sync_entries: load(&self.buffer_sync_entries),
            buffer_sync_bytes: load(&self.buffer_sync_bytes),
            buffer_sync_entries_max: load(&self.buffer_sync_entries_max),
            buffer_sync_bytes_max: load(&self.buffer_sync_bytes_max),
            buffer_backpressure_events: load(&self.buffer_backpressure_events),
            buffer_backpressure_wait_ns: load(&self.buffer_backpressure_wait_ns),
            buffer_throttle_count: load(&self.buffer_throttle_count),
            buffer_throttle_us_total: load(&self.buffer_throttle_us_total),
            buffer_throttle_us_max: load(&self.buffer_throttle_us_max),
            buffer_hydration_skipped_due_to_mem_limit: load(
                &self.buffer_hydration_skipped_due_to_mem_limit,
            ),
            buffer_hydration_head_bypass_count: load(&self.buffer_hydration_head_bypass_count),
            buffer_payload_cache_evict_entries: load(&self.buffer_payload_cache_evict_entries),
            buffer_payload_cache_evict_bytes: load(&self.buffer_payload_cache_evict_bytes),
            buffer_lookup_hits: load(&self.buffer_lookup_hits),
            buffer_lookup_misses: load(&self.buffer_lookup_misses),
            buffer_lookup_index_ns: load(&self.buffer_lookup_index_ns),
            buffer_lookup_hydrate_ns: load(&self.buffer_lookup_hydrate_ns),
            buffer_lookup_hydrate_ops: load(&self.buffer_lookup_hydrate_ops),
            buffer_coalesce_hydrate_ns: load(&self.buffer_coalesce_hydrate_ns),
            buffer_coalesce_hydrate_ops: load(&self.buffer_coalesce_hydrate_ops),
            buffer_coalesce_hydrate_entries: load(&self.buffer_coalesce_hydrate_entries),
            buffer_coalesce_hydrate_memory_entries: load(
                &self.buffer_coalesce_hydrate_memory_entries,
            ),
            buffer_coalesce_hydrate_volatile_entries: load(
                &self.buffer_coalesce_hydrate_volatile_entries,
            ),
            buffer_coalesce_hydrate_disk_entries: load(&self.buffer_coalesce_hydrate_disk_entries),
            buffer_coalesce_hydrate_inflight_skips: load(
                &self.buffer_coalesce_hydrate_inflight_skips,
            ),
            buffer_read_ops: load(&self.buffer_read_ops),
            buffer_read_bytes: load(&self.buffer_read_bytes),
            read_buffer_hits: load(&self.read_buffer_hits),
            read_lv3_hits: load(&self.read_lv3_hits),
            lv3_read_ops: load(&self.lv3_read_ops),
            lv3_read_compressed_bytes: load(&self.lv3_read_compressed_bytes),
            lv3_read_decompressed_bytes: load(&self.lv3_read_decompressed_bytes),
            read_pool_requests: load(&self.read_pool_requests),
            read_pool_batches: load(&self.read_pool_batches),
            read_pool_batch_ops: load(&self.read_pool_batch_ops),
            read_pool_queue_wait_ns: load(&self.read_pool_queue_wait_ns),
            read_pool_coalesce_wait_ns: load(&self.read_pool_coalesce_wait_ns),
            read_pool_alloc_ns: load(&self.read_pool_alloc_ns),
            read_pool_submit_wait_ns: load(&self.read_pool_submit_wait_ns),
            read_pool_decode_ns: load(&self.read_pool_decode_ns),
            read_pool_queue_wait_latency_buckets: load_latency_buckets(
                &self.read_pool_queue_wait_latency_buckets,
            ),
            read_pool_submit_wait_latency_buckets: load_latency_buckets(
                &self.read_pool_submit_wait_latency_buckets,
            ),
            read_pool_decode_latency_buckets: load_latency_buckets(
                &self.read_pool_decode_latency_buckets,
            ),
            read_pool_worker_requests: load_atomic_slice(&self.read_pool_worker_requests),
            read_pool_worker_batches: load_atomic_slice(&self.read_pool_worker_batches),
            read_pool_worker_queue_wait_ns: load_atomic_slice(&self.read_pool_worker_queue_wait_ns),
            read_pool_worker_submit_wait_ns: load_atomic_slice(
                &self.read_pool_worker_submit_wait_ns,
            ),
            lv3_write_ops: load(&self.lv3_write_ops),
            lv3_write_compressed_bytes: load(&self.lv3_write_compressed_bytes),
            lv3_write_batch_calls: load(&self.lv3_write_batch_calls),
            lv3_write_batch_ops: load(&self.lv3_write_batch_ops),
            lv3_write_batch_bytes: load(&self.lv3_write_batch_bytes),
            lv3_write_slab_allocs: load(&self.lv3_write_slab_allocs),
            lv3_write_slab_bytes: load(&self.lv3_write_slab_bytes),
            read_unmapped: load(&self.read_unmapped),
            read_crc_errors: load(&self.read_crc_errors),
            read_crc_errors_foreground: load(&self.read_crc_errors_foreground),
            dedup_verify_mismatches: load(&self.dedup_verify_mismatches),
            read_crc_errors_dedup_scanner: load(&self.read_crc_errors_dedup_scanner),
            read_decompress_errors: load(&self.read_decompress_errors),
            read_submit_calls: load(&self.read_submit_calls),
            read_submit_total_ns: load(&self.read_submit_total_ns),
            read_submit_buffer_lookup_ns: load(&self.read_submit_buffer_lookup_ns),
            read_submit_meta_get_ns: load(&self.read_submit_meta_get_ns),
            read_submit_meta_query_ns: load(&self.read_submit_meta_query_ns),
            read_submit_meta_route_ns: load(&self.read_submit_meta_route_ns),
            read_submit_unit_io_ns: load(&self.read_submit_unit_io_ns),
            read_submit_unit_io_latency_buckets: load_latency_buckets(
                &self.read_submit_unit_io_latency_buckets,
            ),
            coalesce_runs: load(&self.coalesce_runs),
            coalesced_units: load(&self.coalesced_units),
            coalesced_lbas: load(&self.coalesced_lbas),
            coalesced_bytes: load(&self.coalesced_bytes),
            coalesce_superseded_entries: load(&self.coalesce_superseded_entries),
            coalesce_superseded_lbas: load(&self.coalesce_superseded_lbas),
            compress_units: load(&self.compress_units),
            compress_input_bytes: load(&self.compress_input_bytes),
            compress_output_bytes: load(&self.compress_output_bytes),
            compress_bypass_units: load(&self.compress_bypass_units),
            compress_bypass_bytes: load(&self.compress_bypass_bytes),
            dedup_hits: load(&self.dedup_hits),
            dedup_misses: load(&self.dedup_misses),
            dedup_skipped_units: load(&self.dedup_skipped_units),
            dedup_hit_failures: load(&self.dedup_hit_failures),
            dedup_lookup_ops: load(&self.dedup_lookup_ops),
            dedup_lookup_ns: load(&self.dedup_lookup_ns),
            dedup_live_check_ops: load(&self.dedup_live_check_ops),
            dedup_live_check_ns: load(&self.dedup_live_check_ns),
            dedup_stale_index_entries: load(&self.dedup_stale_index_entries),
            dedup_stale_delete_ns: load(&self.dedup_stale_delete_ns),
            dedup_hit_commit_ops: load(&self.dedup_hit_commit_ops),
            dedup_hit_commit_ns: load(&self.dedup_hit_commit_ns),
            dedup_promotions_committed: load(&self.dedup_promotions_committed),
            dedup_promotions_failed: load(&self.dedup_promotions_failed),
            dedup_cleanup_reconstruct_errors: load(&self.dedup_cleanup_reconstruct_errors),
            dedup_cleanup_delete_errors: load(&self.dedup_cleanup_delete_errors),
            flush_units_written: load(&self.flush_units_written),
            flush_unit_bytes: load(&self.flush_unit_bytes),
            flush_packed_slots_written: load(&self.flush_packed_slots_written),
            flush_packed_fragments_written: load(&self.flush_packed_fragments_written),
            flush_packed_bytes: load(&self.flush_packed_bytes),
            flush_stale_discards: load(&self.flush_stale_discards),
            flush_seq_rejects: load(&self.flush_seq_rejects),
            flush_errors: load(&self.flush_errors),
            flush_writer_total_ns: load(&self.flush_writer_total_ns),
            flush_writer_alloc_ns: load(&self.flush_writer_alloc_ns),
            flush_writer_io_ns: load(&self.flush_writer_io_ns),
            flush_writer_meta_ns: load(&self.flush_writer_meta_ns),
            flush_writer_meta_build_ns: load(&self.flush_writer_meta_build_ns),
            flush_writer_meta_commit_ns: load(&self.flush_writer_meta_commit_ns),
            flush_writer_meta_candidate_ns: load(&self.flush_writer_meta_candidate_ns),
            flush_writer_meta_repair_ns: load(&self.flush_writer_meta_repair_ns),
            flush_writer_meta_commits: load(&self.flush_writer_meta_commits),
            flush_writer_meta_lbas: load(&self.flush_writer_meta_lbas),
            flush_writer_meta_pt_commits: load(&self.flush_writer_meta_pt_commits),
            flush_writer_meta_pt_lbas: load(&self.flush_writer_meta_pt_lbas),
            flush_writer_meta_packed_commits: load(&self.flush_writer_meta_packed_commits),
            flush_writer_meta_packed_lbas: load(&self.flush_writer_meta_packed_lbas),
            flush_writer_cycles: load(&self.flush_writer_cycles),
            flush_writer_cycles_full: load(&self.flush_writer_cycles_full),
            flush_writer_cycles_partial: load(&self.flush_writer_cycles_partial),
            flush_writer_read_active_cycles: load(&self.flush_writer_read_active_cycles),
            flush_writer_drained_units: load(&self.flush_writer_drained_units),
            flush_writer_drained_units_max: load(&self.flush_writer_drained_units_max),
            flush_writer_rx_pending_max: load(&self.flush_writer_rx_pending_max),
            flush_writer_commit_send_ns: load(&self.flush_writer_commit_send_ns),
            flush_writer_commit_send_ops: load(&self.flush_writer_commit_send_ops),
            flush_writer_commit_send_len_max: load(&self.flush_writer_commit_send_len_max),
            flush_commit_worker_queue_wait_ns: load(&self.flush_commit_worker_queue_wait_ns),
            flush_commit_worker_service_ns: load(&self.flush_commit_worker_service_ns),
            flush_commit_worker_jobs: load(&self.flush_commit_worker_jobs),
            flush_commit_worker_job_lbas: load(&self.flush_commit_worker_job_lbas),
            flush_commit_worker_drain_batches: load(&self.flush_commit_worker_drain_batches),
            flush_commit_worker_drain_jobs: load(&self.flush_commit_worker_drain_jobs),
            flush_commit_worker_drain_lbas: load(&self.flush_commit_worker_drain_lbas),
            flush_commit_worker_drain_jobs_max: load(&self.flush_commit_worker_drain_jobs_max),
            flush_commit_worker_drain_lbas_max: load(&self.flush_commit_worker_drain_lbas_max),
            flush_stage_coalesce_send_ns: load(&self.flush_stage_coalesce_send_ns),
            flush_stage_coalesce_send_ops: load(&self.flush_stage_coalesce_send_ops),
            flush_stage_coalesce_send_len_sum: load(&self.flush_stage_coalesce_send_len_sum),
            flush_stage_coalesce_send_len_max: load(&self.flush_stage_coalesce_send_len_max),
            flush_stage_dedup_send_ns: load(&self.flush_stage_dedup_send_ns),
            flush_stage_dedup_send_ops: load(&self.flush_stage_dedup_send_ops),
            flush_stage_dedup_send_len_sum: load(&self.flush_stage_dedup_send_len_sum),
            flush_stage_dedup_send_len_max: load(&self.flush_stage_dedup_send_len_max),
            flush_stage_compress_send_ns: load(&self.flush_stage_compress_send_ns),
            flush_stage_compress_send_ops: load(&self.flush_stage_compress_send_ops),
            flush_stage_compress_send_len_sum: load(&self.flush_stage_compress_send_len_sum),
            flush_stage_compress_send_len_max: load(&self.flush_stage_compress_send_len_max),
            flush_coalesce_active_ns: load(&self.flush_coalesce_active_ns),
            flush_coalesce_idle_ns: load(&self.flush_coalesce_idle_ns),
            flush_coalesce_pending_ns: load(&self.flush_coalesce_pending_ns),
            flush_coalesce_pending_ops: load(&self.flush_coalesce_pending_ops),
            flush_coalesce_phase2_dedup_ns: load(&self.flush_coalesce_phase2_dedup_ns),
            flush_coalesce_phase3_sort_ns: load(&self.flush_coalesce_phase3_sort_ns),
            flush_coalesce_phase4_merge_ns: load(&self.flush_coalesce_phase4_merge_ns),
            flush_dedup_worker_active_ns: load(&self.flush_dedup_worker_active_ns),
            flush_dedup_worker_idle_ns: load(&self.flush_dedup_worker_idle_ns),
            flush_dedup_worker_iters: load(&self.flush_dedup_worker_iters),
            flush_compress_worker_active_ns: load(&self.flush_compress_worker_active_ns),
            flush_compress_worker_idle_ns: load(&self.flush_compress_worker_idle_ns),
            flush_compress_raw_build_ns: load(&self.flush_compress_raw_build_ns),
            flush_compress_codec_ns: load(&self.flush_compress_codec_ns),
            flush_compress_crc_ns: load(&self.flush_compress_crc_ns),
            flush_commit_worker_rx_idle_ns: load(&self.flush_commit_worker_rx_idle_ns),
            flush_commit_worker_rx_idle_iters: load(&self.flush_commit_worker_rx_idle_iters),
            flush_writer_pt_batches: load(&self.flush_writer_pt_batches),
            flush_writer_pt_units: load(&self.flush_writer_pt_units),
            flush_writer_pt_lbas: load(&self.flush_writer_pt_lbas),
            flush_writer_pt_io_ops: load(&self.flush_writer_pt_io_ops),
            flush_writer_pt_mark_calls: load(&self.flush_writer_pt_mark_calls),
            flush_writer_pt_mark_lbas: load(&self.flush_writer_pt_mark_lbas),
            flush_writer_pt_units_max: load(&self.flush_writer_pt_units_max),
            flush_writer_pt_lbas_max: load(&self.flush_writer_pt_lbas_max),
            flush_writer_pt_io_ops_max: load(&self.flush_writer_pt_io_ops_max),
            flush_writer_pt_mark_calls_max: load(&self.flush_writer_pt_mark_calls_max),
            flush_writer_packed_batches: load(&self.flush_writer_packed_batches),
            flush_writer_packed_batch_slots: load(&self.flush_writer_packed_batch_slots),
            flush_writer_packed_batch_lbas: load(&self.flush_writer_packed_batch_lbas),
            flush_writer_packed_batch_io_ops: load(&self.flush_writer_packed_batch_io_ops),
            flush_writer_packed_mark_calls: load(&self.flush_writer_packed_mark_calls),
            flush_writer_packed_mark_lbas: load(&self.flush_writer_packed_mark_lbas),
            flush_writer_packed_batch_slots_max: load(&self.flush_writer_packed_batch_slots_max),
            flush_writer_packed_batch_lbas_max: load(&self.flush_writer_packed_batch_lbas_max),
            flush_writer_packed_batch_io_ops_max: load(&self.flush_writer_packed_batch_io_ops_max),
            flush_writer_packed_mark_calls_max: load(&self.flush_writer_packed_mark_calls_max),
            flush_writer_cleanup_ns: load(&self.flush_writer_cleanup_ns),
            flush_cleanup_thread_ns: load(&self.flush_cleanup_thread_ns),
            flush_cleanup_thread_batches: load(&self.flush_cleanup_thread_batches),
            flush_writer_dedup_index_ns: load(&self.flush_writer_dedup_index_ns),
            flush_writer_mark_flushed_ns: load(&self.flush_writer_mark_flushed_ns),
            flush_writer_precheck_live_pba_ops: load(&self.flush_writer_precheck_live_pba_ops),
            flush_writer_precheck_live_pba_ns: load(&self.flush_writer_precheck_live_pba_ns),
            flush_writer_precheck_live_pba_failures: load(
                &self.flush_writer_precheck_live_pba_failures,
            ),
            gc_cycles: load(&self.gc_cycles),
            gc_paused_cycles: load(&self.gc_paused_cycles),
            gc_candidates_found: load(&self.gc_candidates_found),
            gc_rewrite_attempts: load(&self.gc_rewrite_attempts),
            gc_blocks_rewritten: load(&self.gc_blocks_rewritten),
            gc_retired_blocks_reclaimed: load(&self.gc_retired_blocks_reclaimed),
            gc_errors: load(&self.gc_errors),
            gc_lineage_freed_blocks: load(&self.gc_lineage_freed_blocks),
            dedup_rescan_cycles: load(&self.dedup_rescan_cycles),
            dedup_rescan_skipped_cycles: load(&self.dedup_rescan_skipped_cycles),
            dedup_rescan_blocks: load(&self.dedup_rescan_blocks),
            dedup_rescan_hits: load(&self.dedup_rescan_hits),
            dedup_rescan_misses: load(&self.dedup_rescan_misses),
            dedup_rescan_errors: load(&self.dedup_rescan_errors),
            dedup_cold_tail_blocks: load(&self.dedup_cold_tail_blocks),
            dedup_cold_tail_already_warm: load(&self.dedup_cold_tail_already_warm),
            dedup_cold_tail_errors: load(&self.dedup_cold_tail_errors),
            volume_discard_ops: load(&self.volume_discard_ops),
            volume_discard_lbas: load(&self.volume_discard_lbas),
            discard_blocks_freed: load(&self.discard_blocks_freed),
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize)]
pub struct EngineMetricsSnapshot {
    pub uptime_secs: u64,
    pub volume_create_ops: u64,
    pub volume_delete_ops: u64,
    pub volume_open_ops: u64,
    pub volume_read_ops: u64,
    pub volume_read_bytes: u64,
    pub volume_read_total_ns: u64,
    pub ublk_read_queue_wait_ns: u64,
    pub ublk_read_worker_ns: u64,
    pub ublk_read_completion_wait_ns: u64,
    pub volume_partial_read_ops: u64,
    pub volume_write_ops: u64,
    pub volume_write_bytes: u64,
    pub volume_write_total_ns: u64,
    pub ublk_write_queue_wait_ns: u64,
    pub ublk_write_worker_ns: u64,
    pub ublk_write_completion_wait_ns: u64,
    pub volume_partial_write_ops: u64,
    pub zone_write_dispatches: u64,
    pub zone_submit_write_ns: u64,
    pub zone_worker_write_ns: u64,
    pub zone_write_split_ops: u64,
    pub zone_write_lbas: u64,
    pub zone_read_dispatches: u64,
    pub buffer_appends: u64,
    pub buffer_append_bytes: u64,
    pub buffer_write_ops: u64,
    pub buffer_write_bytes: u64,
    pub buffer_append_total_ns: u64,
    pub buffer_append_prepare_ns: u64,
    pub buffer_append_log_write_ns: u64,
    pub buffer_append_wait_durable_ns: u64,
    pub buffer_sync_batches: u64,
    pub buffer_sync_batch_ns: u64,
    pub buffer_sync_sleep_ns: u64,
    pub buffer_sync_epochs_committed: u64,
    pub buffer_sync_entries: u64,
    pub buffer_sync_bytes: u64,
    pub buffer_sync_entries_max: u64,
    pub buffer_sync_bytes_max: u64,
    pub buffer_backpressure_events: u64,
    pub buffer_backpressure_wait_ns: u64,
    pub buffer_throttle_count: u64,
    pub buffer_throttle_us_total: u64,
    pub buffer_throttle_us_max: u64,
    pub buffer_hydration_skipped_due_to_mem_limit: u64,
    pub buffer_hydration_head_bypass_count: u64,
    pub buffer_payload_cache_evict_entries: u64,
    pub buffer_payload_cache_evict_bytes: u64,
    pub buffer_lookup_hits: u64,
    pub buffer_lookup_misses: u64,
    pub buffer_lookup_index_ns: u64,
    pub buffer_lookup_hydrate_ns: u64,
    pub buffer_lookup_hydrate_ops: u64,
    pub buffer_coalesce_hydrate_ns: u64,
    pub buffer_coalesce_hydrate_ops: u64,
    pub buffer_coalesce_hydrate_entries: u64,
    pub buffer_coalesce_hydrate_memory_entries: u64,
    pub buffer_coalesce_hydrate_volatile_entries: u64,
    pub buffer_coalesce_hydrate_disk_entries: u64,
    pub buffer_coalesce_hydrate_inflight_skips: u64,
    pub buffer_read_ops: u64,
    pub buffer_read_bytes: u64,
    pub read_buffer_hits: u64,
    pub read_lv3_hits: u64,
    pub lv3_read_ops: u64,
    pub lv3_read_compressed_bytes: u64,
    pub lv3_read_decompressed_bytes: u64,
    pub read_pool_requests: u64,
    pub read_pool_batches: u64,
    pub read_pool_batch_ops: u64,
    pub read_pool_queue_wait_ns: u64,
    pub read_pool_coalesce_wait_ns: u64,
    pub read_pool_alloc_ns: u64,
    pub read_pool_submit_wait_ns: u64,
    pub read_pool_decode_ns: u64,
    pub read_pool_queue_wait_latency_buckets: Vec<u64>,
    pub read_pool_submit_wait_latency_buckets: Vec<u64>,
    pub read_pool_decode_latency_buckets: Vec<u64>,
    pub read_pool_worker_requests: Vec<u64>,
    pub read_pool_worker_batches: Vec<u64>,
    pub read_pool_worker_queue_wait_ns: Vec<u64>,
    pub read_pool_worker_submit_wait_ns: Vec<u64>,
    pub lv3_write_ops: u64,
    pub lv3_write_compressed_bytes: u64,
    pub lv3_write_batch_calls: u64,
    pub lv3_write_batch_ops: u64,
    pub lv3_write_batch_bytes: u64,
    pub lv3_write_slab_allocs: u64,
    pub lv3_write_slab_bytes: u64,
    pub read_unmapped: u64,
    pub read_crc_errors: u64,
    pub read_crc_errors_foreground: u64,
    pub dedup_verify_mismatches: u64,
    pub read_crc_errors_dedup_scanner: u64,
    pub read_decompress_errors: u64,
    pub read_submit_calls: u64,
    pub read_submit_total_ns: u64,
    pub read_submit_buffer_lookup_ns: u64,
    pub read_submit_meta_get_ns: u64,
    pub read_submit_meta_query_ns: u64,
    pub read_submit_meta_route_ns: u64,
    pub read_submit_unit_io_ns: u64,
    pub read_submit_unit_io_latency_buckets: Vec<u64>,
    pub coalesce_runs: u64,
    pub coalesced_units: u64,
    pub coalesced_lbas: u64,
    pub coalesced_bytes: u64,
    pub coalesce_superseded_entries: u64,
    pub coalesce_superseded_lbas: u64,
    pub compress_units: u64,
    pub compress_input_bytes: u64,
    pub compress_output_bytes: u64,
    pub compress_bypass_units: u64,
    pub compress_bypass_bytes: u64,
    pub dedup_hits: u64,
    pub dedup_misses: u64,
    pub dedup_skipped_units: u64,
    pub dedup_hit_failures: u64,
    pub dedup_lookup_ops: u64,
    pub dedup_lookup_ns: u64,
    pub dedup_live_check_ops: u64,
    pub dedup_live_check_ns: u64,
    pub dedup_stale_index_entries: u64,
    pub dedup_stale_delete_ns: u64,
    pub dedup_hit_commit_ops: u64,
    pub dedup_hit_commit_ns: u64,
    pub dedup_promotions_committed: u64,
    pub dedup_promotions_failed: u64,
    pub dedup_cleanup_reconstruct_errors: u64,
    pub dedup_cleanup_delete_errors: u64,
    pub flush_units_written: u64,
    pub flush_unit_bytes: u64,
    pub flush_packed_slots_written: u64,
    pub flush_packed_fragments_written: u64,
    pub flush_packed_bytes: u64,
    pub flush_stale_discards: u64,
    pub flush_seq_rejects: u64,
    pub flush_errors: u64,
    pub flush_writer_total_ns: u64,
    pub flush_writer_alloc_ns: u64,
    pub flush_writer_io_ns: u64,
    pub flush_writer_meta_ns: u64,
    pub flush_writer_meta_build_ns: u64,
    pub flush_writer_meta_commit_ns: u64,
    pub flush_writer_meta_candidate_ns: u64,
    pub flush_writer_meta_repair_ns: u64,
    pub flush_writer_meta_commits: u64,
    pub flush_writer_meta_lbas: u64,
    pub flush_writer_meta_pt_commits: u64,
    pub flush_writer_meta_pt_lbas: u64,
    pub flush_writer_meta_packed_commits: u64,
    pub flush_writer_meta_packed_lbas: u64,
    pub flush_writer_cycles: u64,
    pub flush_writer_cycles_full: u64,
    pub flush_writer_cycles_partial: u64,
    pub flush_writer_read_active_cycles: u64,
    pub flush_writer_drained_units: u64,
    pub flush_writer_drained_units_max: u64,
    pub flush_writer_rx_pending_max: u64,
    pub flush_writer_commit_send_ns: u64,
    pub flush_writer_commit_send_ops: u64,
    pub flush_writer_commit_send_len_max: u64,
    pub flush_commit_worker_queue_wait_ns: u64,
    pub flush_commit_worker_service_ns: u64,
    pub flush_commit_worker_jobs: u64,
    pub flush_commit_worker_job_lbas: u64,
    pub flush_commit_worker_drain_batches: u64,
    pub flush_commit_worker_drain_jobs: u64,
    pub flush_commit_worker_drain_lbas: u64,
    pub flush_commit_worker_drain_jobs_max: u64,
    pub flush_commit_worker_drain_lbas_max: u64,
    pub flush_stage_coalesce_send_ns: u64,
    pub flush_stage_coalesce_send_ops: u64,
    pub flush_stage_coalesce_send_len_sum: u64,
    pub flush_stage_coalesce_send_len_max: u64,
    pub flush_stage_dedup_send_ns: u64,
    pub flush_stage_dedup_send_ops: u64,
    pub flush_stage_dedup_send_len_sum: u64,
    pub flush_stage_dedup_send_len_max: u64,
    pub flush_stage_compress_send_ns: u64,
    pub flush_stage_compress_send_ops: u64,
    pub flush_stage_compress_send_len_sum: u64,
    pub flush_stage_compress_send_len_max: u64,
    pub flush_coalesce_active_ns: u64,
    pub flush_coalesce_idle_ns: u64,
    pub flush_coalesce_pending_ns: u64,
    pub flush_coalesce_pending_ops: u64,
    pub flush_coalesce_phase2_dedup_ns: u64,
    pub flush_coalesce_phase3_sort_ns: u64,
    pub flush_coalesce_phase4_merge_ns: u64,
    pub flush_dedup_worker_active_ns: u64,
    pub flush_dedup_worker_idle_ns: u64,
    pub flush_dedup_worker_iters: u64,
    pub flush_compress_worker_active_ns: u64,
    pub flush_compress_worker_idle_ns: u64,
    pub flush_compress_raw_build_ns: u64,
    pub flush_compress_codec_ns: u64,
    pub flush_compress_crc_ns: u64,
    pub flush_commit_worker_rx_idle_ns: u64,
    pub flush_commit_worker_rx_idle_iters: u64,
    pub flush_writer_pt_batches: u64,
    pub flush_writer_pt_units: u64,
    pub flush_writer_pt_lbas: u64,
    pub flush_writer_pt_io_ops: u64,
    pub flush_writer_pt_mark_calls: u64,
    pub flush_writer_pt_mark_lbas: u64,
    pub flush_writer_pt_units_max: u64,
    pub flush_writer_pt_lbas_max: u64,
    pub flush_writer_pt_io_ops_max: u64,
    pub flush_writer_pt_mark_calls_max: u64,
    pub flush_writer_packed_batches: u64,
    pub flush_writer_packed_batch_slots: u64,
    pub flush_writer_packed_batch_lbas: u64,
    pub flush_writer_packed_batch_io_ops: u64,
    pub flush_writer_packed_mark_calls: u64,
    pub flush_writer_packed_mark_lbas: u64,
    pub flush_writer_packed_batch_slots_max: u64,
    pub flush_writer_packed_batch_lbas_max: u64,
    pub flush_writer_packed_batch_io_ops_max: u64,
    pub flush_writer_packed_mark_calls_max: u64,
    pub flush_writer_cleanup_ns: u64,
    pub flush_cleanup_thread_ns: u64,
    pub flush_cleanup_thread_batches: u64,
    pub flush_writer_dedup_index_ns: u64,
    pub flush_writer_mark_flushed_ns: u64,
    pub flush_writer_precheck_live_pba_ops: u64,
    pub flush_writer_precheck_live_pba_ns: u64,
    pub flush_writer_precheck_live_pba_failures: u64,
    pub gc_cycles: u64,
    pub gc_paused_cycles: u64,
    pub gc_candidates_found: u64,
    pub gc_rewrite_attempts: u64,
    pub gc_blocks_rewritten: u64,
    pub gc_retired_blocks_reclaimed: u64,
    pub gc_errors: u64,
    pub gc_lineage_freed_blocks: u64,
    pub dedup_rescan_cycles: u64,
    pub dedup_rescan_skipped_cycles: u64,
    pub dedup_rescan_blocks: u64,
    pub dedup_rescan_hits: u64,
    pub dedup_rescan_misses: u64,
    pub dedup_rescan_errors: u64,
    pub dedup_cold_tail_blocks: u64,
    pub dedup_cold_tail_already_warm: u64,
    pub dedup_cold_tail_errors: u64,
    pub volume_discard_ops: u64,
    pub volume_discard_lbas: u64,
    pub discard_blocks_freed: u64,
}

impl EngineMetricsSnapshot {
    pub fn saturating_sub(&self, earlier: &Self) -> Self {
        macro_rules! build_sub {
            ($($field:ident),+ $(,)?) => {
                Self {
                    $(
                        $field: self.$field.saturating_sub(earlier.$field),
                    )+
                    read_pool_queue_wait_latency_buckets: sub_latency_buckets(
                        &self.read_pool_queue_wait_latency_buckets,
                        &earlier.read_pool_queue_wait_latency_buckets,
                    ),
                    read_pool_submit_wait_latency_buckets: sub_latency_buckets(
                        &self.read_pool_submit_wait_latency_buckets,
                        &earlier.read_pool_submit_wait_latency_buckets,
                    ),
                    read_pool_decode_latency_buckets: sub_latency_buckets(
                        &self.read_pool_decode_latency_buckets,
                        &earlier.read_pool_decode_latency_buckets,
                    ),
                    read_pool_worker_requests: sub_latency_buckets(
                        &self.read_pool_worker_requests,
                        &earlier.read_pool_worker_requests,
                    ),
                    read_pool_worker_batches: sub_latency_buckets(
                        &self.read_pool_worker_batches,
                        &earlier.read_pool_worker_batches,
                    ),
                    read_pool_worker_queue_wait_ns: sub_latency_buckets(
                        &self.read_pool_worker_queue_wait_ns,
                        &earlier.read_pool_worker_queue_wait_ns,
                    ),
                    read_pool_worker_submit_wait_ns: sub_latency_buckets(
                        &self.read_pool_worker_submit_wait_ns,
                        &earlier.read_pool_worker_submit_wait_ns,
                    ),
                    read_submit_unit_io_latency_buckets: sub_latency_buckets(
                        &self.read_submit_unit_io_latency_buckets,
                        &earlier.read_submit_unit_io_latency_buckets,
                    ),
                }
            };
        }

        build_sub! {
            uptime_secs,
            volume_create_ops,
            volume_delete_ops,
            volume_open_ops,
            volume_read_ops,
            volume_read_bytes,
            volume_read_total_ns,
            ublk_read_queue_wait_ns,
            ublk_read_worker_ns,
            ublk_read_completion_wait_ns,
            volume_partial_read_ops,
            volume_write_ops,
            volume_write_bytes,
            volume_write_total_ns,
            ublk_write_queue_wait_ns,
            ublk_write_worker_ns,
            ublk_write_completion_wait_ns,
            volume_partial_write_ops,
            zone_write_dispatches,
            zone_submit_write_ns,
            zone_worker_write_ns,
            zone_write_split_ops,
            zone_write_lbas,
            zone_read_dispatches,
            buffer_appends,
            buffer_append_bytes,
            buffer_write_ops,
            buffer_write_bytes,
            buffer_append_total_ns,
            buffer_append_prepare_ns,
            buffer_append_log_write_ns,
            buffer_append_wait_durable_ns,
            buffer_sync_batches,
            buffer_sync_batch_ns,
            buffer_sync_sleep_ns,
            buffer_sync_epochs_committed,
            buffer_sync_entries,
            buffer_sync_bytes,
            buffer_sync_entries_max,
            buffer_sync_bytes_max,
            buffer_backpressure_events,
            buffer_backpressure_wait_ns,
            buffer_throttle_count,
            buffer_throttle_us_total,
            buffer_throttle_us_max,
            buffer_hydration_skipped_due_to_mem_limit,
            buffer_hydration_head_bypass_count,
            buffer_payload_cache_evict_entries,
            buffer_payload_cache_evict_bytes,
            buffer_lookup_hits,
            buffer_lookup_misses,
            buffer_lookup_index_ns,
            buffer_lookup_hydrate_ns,
            buffer_lookup_hydrate_ops,
            buffer_coalesce_hydrate_ns,
            buffer_coalesce_hydrate_ops,
            buffer_coalesce_hydrate_entries,
            buffer_coalesce_hydrate_memory_entries,
            buffer_coalesce_hydrate_volatile_entries,
            buffer_coalesce_hydrate_disk_entries,
            buffer_coalesce_hydrate_inflight_skips,
            buffer_read_ops,
            buffer_read_bytes,
            read_buffer_hits,
            read_lv3_hits,
            lv3_read_ops,
            lv3_read_compressed_bytes,
            lv3_read_decompressed_bytes,
            read_pool_requests,
            read_pool_batches,
            read_pool_batch_ops,
            read_pool_queue_wait_ns,
            read_pool_coalesce_wait_ns,
            read_pool_alloc_ns,
            read_pool_submit_wait_ns,
            read_pool_decode_ns,
            lv3_write_ops,
            lv3_write_compressed_bytes,
            lv3_write_batch_calls,
            lv3_write_batch_ops,
            lv3_write_batch_bytes,
            lv3_write_slab_allocs,
            lv3_write_slab_bytes,
            read_unmapped,
            read_crc_errors,
            read_crc_errors_foreground,
            dedup_verify_mismatches,
            read_crc_errors_dedup_scanner,
            read_decompress_errors,
            read_submit_calls,
            read_submit_total_ns,
            read_submit_buffer_lookup_ns,
            read_submit_meta_get_ns,
            read_submit_meta_query_ns,
            read_submit_meta_route_ns,
            read_submit_unit_io_ns,
            coalesce_runs,
            coalesced_units,
            coalesced_lbas,
            coalesced_bytes,
            coalesce_superseded_entries,
            coalesce_superseded_lbas,
            compress_units,
            compress_input_bytes,
            compress_output_bytes,
            compress_bypass_units,
            compress_bypass_bytes,
            dedup_hits,
            dedup_misses,
            dedup_skipped_units,
            dedup_hit_failures,
            dedup_lookup_ops,
            dedup_lookup_ns,
            dedup_live_check_ops,
            dedup_live_check_ns,
            dedup_stale_index_entries,
            dedup_stale_delete_ns,
            dedup_hit_commit_ops,
            dedup_hit_commit_ns,
            dedup_promotions_committed,
            dedup_promotions_failed,
            dedup_cleanup_reconstruct_errors,
            dedup_cleanup_delete_errors,
            flush_units_written,
            flush_unit_bytes,
            flush_packed_slots_written,
            flush_packed_fragments_written,
            flush_packed_bytes,
            flush_stale_discards,
            flush_seq_rejects,
            flush_errors,
            flush_writer_total_ns,
            flush_writer_alloc_ns,
            flush_writer_io_ns,
            flush_writer_meta_ns,
            flush_writer_meta_build_ns,
            flush_writer_meta_commit_ns,
            flush_writer_meta_candidate_ns,
            flush_writer_meta_repair_ns,
            flush_writer_meta_commits,
            flush_writer_meta_lbas,
            flush_writer_meta_pt_commits,
            flush_writer_meta_pt_lbas,
            flush_writer_meta_packed_commits,
            flush_writer_meta_packed_lbas,
            flush_writer_cycles,
            flush_writer_cycles_full,
            flush_writer_cycles_partial,
            flush_writer_read_active_cycles,
            flush_writer_drained_units,
            flush_writer_drained_units_max,
            flush_writer_rx_pending_max,
            flush_writer_commit_send_ns,
            flush_writer_commit_send_ops,
            flush_writer_commit_send_len_max,
            flush_commit_worker_queue_wait_ns,
            flush_commit_worker_service_ns,
            flush_commit_worker_jobs,
            flush_commit_worker_job_lbas,
            flush_commit_worker_drain_batches,
            flush_commit_worker_drain_jobs,
            flush_commit_worker_drain_lbas,
            flush_commit_worker_drain_jobs_max,
            flush_commit_worker_drain_lbas_max,
            flush_stage_coalesce_send_ns,
            flush_stage_coalesce_send_ops,
            flush_stage_coalesce_send_len_sum,
            flush_stage_coalesce_send_len_max,
            flush_stage_dedup_send_ns,
            flush_stage_dedup_send_ops,
            flush_stage_dedup_send_len_sum,
            flush_stage_dedup_send_len_max,
            flush_stage_compress_send_ns,
            flush_stage_compress_send_ops,
            flush_stage_compress_send_len_sum,
            flush_stage_compress_send_len_max,
            flush_coalesce_active_ns,
            flush_coalesce_idle_ns,
            flush_coalesce_pending_ns,
            flush_coalesce_pending_ops,
            flush_coalesce_phase2_dedup_ns,
            flush_coalesce_phase3_sort_ns,
            flush_coalesce_phase4_merge_ns,
            flush_dedup_worker_active_ns,
            flush_dedup_worker_idle_ns,
            flush_dedup_worker_iters,
            flush_compress_worker_active_ns,
            flush_compress_worker_idle_ns,
            flush_compress_raw_build_ns,
            flush_compress_codec_ns,
            flush_compress_crc_ns,
            flush_commit_worker_rx_idle_ns,
            flush_commit_worker_rx_idle_iters,
            flush_writer_pt_batches,
            flush_writer_pt_units,
            flush_writer_pt_lbas,
            flush_writer_pt_io_ops,
            flush_writer_pt_mark_calls,
            flush_writer_pt_mark_lbas,
            flush_writer_pt_units_max,
            flush_writer_pt_lbas_max,
            flush_writer_pt_io_ops_max,
            flush_writer_pt_mark_calls_max,
            flush_writer_packed_batches,
            flush_writer_packed_batch_slots,
            flush_writer_packed_batch_lbas,
            flush_writer_packed_batch_io_ops,
            flush_writer_packed_mark_calls,
            flush_writer_packed_mark_lbas,
            flush_writer_packed_batch_slots_max,
            flush_writer_packed_batch_lbas_max,
            flush_writer_packed_batch_io_ops_max,
            flush_writer_packed_mark_calls_max,
            flush_writer_cleanup_ns,
            flush_cleanup_thread_ns,
            flush_cleanup_thread_batches,
            flush_writer_dedup_index_ns,
            flush_writer_mark_flushed_ns,
            flush_writer_precheck_live_pba_ops,
            flush_writer_precheck_live_pba_ns,
            flush_writer_precheck_live_pba_failures,
            gc_cycles,
            gc_paused_cycles,
            gc_candidates_found,
            gc_rewrite_attempts,
            gc_blocks_rewritten,
            gc_retired_blocks_reclaimed,
            gc_errors,
            gc_lineage_freed_blocks,
            dedup_rescan_cycles,
            dedup_rescan_skipped_cycles,
            dedup_rescan_blocks,
            dedup_rescan_hits,
            dedup_rescan_misses,
            dedup_rescan_errors,
            dedup_cold_tail_blocks,
            dedup_cold_tail_already_warm,
            dedup_cold_tail_errors,
            volume_discard_ops,
            volume_discard_lbas,
            discard_blocks_freed,
        }
    }
}
